#Site settings
title: Zombie Potato
email: fisher.rachel.m@gmail.com
author: Rachel M Fisher
description: >- # this means to ignore newlines until "baseurl:"
  Hi I'm Rachel and this is my somewhat eclectic personal blog. It's my place to write about whatever I want whenever I want. I also blog about learning web development at www.rachelmfisher.com.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.zombiepotato.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
permalink: :title/
sass:
  sass_dir: assets
markdown: kramdown
highlighter: rouge

#Social icons
show_social_icons: true
twitter_username: RachelMFisher
github_username:  Elenaltarien

#Plugins
plugins: [jekyll-paginate]
paginate: 3